apiVersion: v1
kind: Namespace
metadata:
  name: exam
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: exam
  name: exam-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: exam-role-binding
  namespace: exam
subjects:
- kind: ServiceAccount
  name: default
  namespace: exam
roleRef:
  kind: ClusterRole
  name: exam-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-keepalive
  namespace: exam
spec:
  selector:
    matchLabels:
      app: exam-keepalive
  replicas: 2
  template:
    metadata:
      labels:
        app: exam-keepalive
    spec:
      containers:
      - env:
        - name: CANDIDATE_NAME
          value: Anonymous
        image: public.ecr.aws/i6v0m5n6/exam-keepalive:0.3
        name: exam-keepalive
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: exam-keepalive
  namespace: exam
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
  selector:
    app: exam-keepalive
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  name: exam-keepalive
  namespace: exam
  labels:
    apps: exam-keepalive
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: exam-keepalive
            port:
              number: 5000
        path: /
        pathType: Prefix
