AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eks-upgrade-exam-backend

Resources:
  AddCandidateFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: add_candidate/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        AddCandidate:
          Type: Api 
          Properties:
            Path: /add_candidate
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref ExamTable      
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExamTable      

  ScrapeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: scrape/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: ScheduleforScrape
            Description: Scrape cluster config for 1 min
            Enabled: false
      Environment:
        Variables:
          TABLE_NAME: !Ref ExamTable             
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExamTable      

  SubmissionFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: submission/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        Submission:
          Type: Api 
          Properties:
            Path: /submission
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref ExamTable                  
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExamTable

  ExamTable: 
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: AWSAccountID
        Type: String
      TableName: ExamTable

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
